service: hello-world

provider:
  name: aws
  runtime: python3.6
  stage: ${env:STAGE, 'dev'}
  region: us-east-1
  deploymentBucket:
    name: tgoncales.lambda-template.deploys

plugins:
  - serverless-python-requirements

custom:
  prefix: ${env:BRANCH_NAME, ''}-
  pythonRequirements:
    dockerizePip: non-linux
 

package:
  exclude:
    - deployment/**
    - node_modules/**
    - tests/**
    - .circleci/**

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET /
      - http: 'GET {proxy+}'
